# Generated by Django 3.2.5 on 2021-08-11 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100, unique=True)),
                ('mobile', models.IntegerField(unique=True)),
                ('address1', models.CharField(default='', max_length=125)),
                ('address2', models.CharField(default='', max_length=125)),
                ('city', models.CharField(default='', max_length=75)),
                ('state', models.CharField(default='', max_length=125)),
                ('password', models.CharField(default='', max_length=20)),
                ('user_type', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
