# Generated by Django 3.2.4 on 2021-07-03 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Public', '0002_rename_users_app_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='App_User',
        ),
    ]
