# Generated by Django 3.2.4 on 2021-07-03 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Public', '0004_app_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='app_user',
            name='first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='app_user',
            name='instrument',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='app_user',
            name='last_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
