# Generated by Django 3.2.4 on 2021-07-03 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Public', '0005_auto_20210703_0747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app_user',
            name='instrument',
        ),
    ]
