# Generated by Django 3.2.4 on 2021-07-03 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Public', '0006_remove_app_user_instrument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app_user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='app_user',
            name='last_name',
        ),
        migrations.AddField(
            model_name='app_user',
            name='address1',
            field=models.CharField(default='-1', max_length=125),
        ),
        migrations.AddField(
            model_name='app_user',
            name='address2',
            field=models.CharField(default='-1', max_length=125),
        ),
        migrations.AddField(
            model_name='app_user',
            name='city',
            field=models.CharField(default='-1', max_length=75),
        ),
        migrations.AddField(
            model_name='app_user',
            name='email',
            field=models.CharField(default='-1', max_length=100),
        ),
        migrations.AddField(
            model_name='app_user',
            name='mobile',
            field=models.IntegerField(default=-1, max_length=10),
        ),
        migrations.AddField(
            model_name='app_user',
            name='name',
            field=models.CharField(default='-1', max_length=100),
        ),
        migrations.AddField(
            model_name='app_user',
            name='password',
            field=models.CharField(default='-1', max_length=20),
        ),
        migrations.AddField(
            model_name='app_user',
            name='state',
            field=models.CharField(default='-1', max_length=125),
        ),
        migrations.AddField(
            model_name='app_user',
            name='user_type',
            field=models.CharField(default='-1', max_length=10),
        ),
    ]
