# Generated by Django 3.2.4 on 2021-07-03 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Public', '0008_auto_20210703_0753'),
    ]

    operations = [
        migrations.DeleteModel(
            name='App_User',
        ),
    ]
